# -*- coding: utf-8 -*-
from __future__ import annotations
import asyncio
import logging
import copy  
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

from modules.platform.abstract_scene_graph import AbstractSceneGraph
from modules.events.event_bus import publish_event_sync
from modules.config.events import NewCaseEvent

logger = logging.getLogger(__name__)


class NewCaseInjector:
    """
    New-case processing pipeline responsible for injection.
    """
    def __init__(
        self,
        scene_graph: AbstractSceneGraph,
        knowledge_scope: str = "local",
        is_replay: bool = False,  
    ) -> None:
        self.scene_graph = scene_graph
        self.knowledge_scope = knowledge_scope

        # Archive completed injections
        self.injected_events: List[Dict[str, Any]] = []

        # Runtime control
        self._running = False

        # Inverse operation queue for dynamic new cases:
        # each item has the shape {"ops": [...], "delay_cycles": int}
        self._rollback_queue: List[Dict[str, Any]] = []

    # --------------------------- Public API ---------------------------

    def set_knowledge_scope(self, scope: str) -> None:
        self.knowledge_scope = scope

    async def inject_event_now(self, event_def: Dict[str, Any]) -> None:
        """
        Apply a fully generated event definition immediately.
        This method executes directly and does not enqueue the event.
        """
        if not event_def or not event_def.get("ops"):
            logger.warning("[NewCaseInjector] Received empty dynamic event; skip.")
            return
        try:
            # Record inverse operations for dynamic events (allow_rollback_record=True)
            success, errors = await self._apply_event_ops(
                event_def,
                allow_rollback_record=True
            )
        except Exception as e:
            success, errors = False, [str(e)]
            logger.error(f"[NewCaseInjector] inject_event_now error: {e}", exc_info=True)

        event_def["success"] = success
        event_def["errors"] = errors
        self._archive_event(event_def, success, errors)

    async def rollback_last_dynamic_event(self) -> bool:
        """
        Roll back part of a dynamic new case generated by NewCaseGenerator
        and applied through inject_event_now.

        Semantics:
        - Each event has delay_cycles (>= 0), meaning how many rollback calls remain before restore.
        - On each call:
            1) First find events with delay_cycles <= 0. If any exist, roll back the first one immediately and return True.
            2) Otherwise, decrement all delay_cycles > 0 values by 1 and return False.
        - This supports:
            * delay_cycles=0 -> restore on the next call.
            * delay_cycles=1 -> restore on the call after next.
        """
        if not self._rollback_queue:
            return False

        # 1) First find already due entries
        ready_idx = None
        for i, item in enumerate(self._rollback_queue):
            if item.get("delay_cycles", 0) <= 0:
                ready_idx = i
                break

        if ready_idx is not None:
            entry = self._rollback_queue.pop(ready_idx)
            ops = entry.get("ops") or []
            if not ops:
                return False

            rollback_event = {
                "id": "rollback-last-dyn",
                "category": "rollback",
                "type": "ROLLBACK",
                "note": "auto rollback of dynamic new-case event",
                "op_template_id": "rollback-auto",
                "ops": ops,
                "trigger": {},
                "success": None,
                "errors": [],
                "event_kind": "recovery",
            }
            success, errors = await self._apply_event_ops(rollback_event, allow_rollback_record=False)
            if not success and errors:
                logger.warning(f"[NewCaseInjector] rollback_last_dynamic_event had errors: {errors}")
            return success

        # 2) If none are due, advance all delay_cycles
        for item in self._rollback_queue:
            d = int(item.get("delay_cycles", 0))
            if d > 0:
                item["delay_cycles"] = d - 1

        return False
    

    async def _apply_event_ops(
        self,
        event_def: Dict[str, Any],
        *, 
        allow_rollback_record: bool = False,
    ) -> Tuple[bool, List[str]]:
        """
        Execute graph operations from an event definition on the scene graph model.
        Operations run in order; failed ops do not stop later ops.
        Returns (whether all succeeded, error list).
        Uses the event definition to decide whether to record inverse operations and their delay cycles.
        """
        ops: List[Dict[str, Any]] = event_def.get("ops") or []
        errors: List[str] = []
        all_ok = True

        event_id = event_def.get("id") or ""
        persist_ops = bool(event_def.get("persist_ops_across_plans"))
        rollback_delay_cycles = int(event_def.get("rollback_delay_cycles", 0))

        # Whether to record inverse operations: only applies to non-persistent dyn-* events
        record_rollback = (
            allow_rollback_record
            and isinstance(event_id, str)
            and event_id.startswith("dyn-")
            and not persist_ops
        )
        rollback_ops: List[Dict[str, Any]] = [] if record_rollback else []

        for op in ops:
            try:
                action = (op.get("action") or "").upper()

                if action == "ADD_NODE":
                    node_data = op.get("node_data") or {}
                    # Inverse operation: delete the newly added node
                    if record_rollback:
                        node_id = node_data.get("id")
                        if node_id is not None:
                            rollback_ops.append({
                                "action": "DELETE_NODE",
                                "node_id": node_id,
                            })
                    ok = self.scene_graph.handle_node_event("add", node_data)

                elif action == "MODIFY_NODE_PROPERTIES":
                    node_id = op.get("node_id")
                    props = op.get("properties") or {}
                    shape = op.get("shape")
                    if not node_id:
                        raise ValueError("MODIFY_NODE_PROPERTIES requires 'node_id'")

                    # Read original node properties/shape before modification to build reverse update
                    if record_rollback:
                        original = self.scene_graph.get_node_by_id(node_id)
                        if original:
                            orig_props = (original.get("properties") or {}).copy()
                            rollback_props: Dict[str, Any] = {}
                            for k in props.keys():
                                if k in orig_props:
                                    rollback_props[k] = orig_props[k]
                            rollback_shape = original.get("shape") if shape is not None else None
                            rb = {"action": "MODIFY_NODE_PROPERTIES", "node_id": node_id}
                            if rollback_props:
                                rb["properties"] = rollback_props
                            if rollback_shape is not None:
                                rb["shape"] = copy.deepcopy(rollback_shape)
                            rollback_ops.append(rb)

                    update_payload: Dict[str, Any] = {"id": node_id}
                    for k, v in props.items():
                        update_payload[k] = v
                    if shape is not None:
                        update_payload["shape"] = shape
                    ok = self.scene_graph.handle_node_event("update", update_payload)

                elif action == "DELETE_NODE":
                    node_id = op.get("node_id")
                    if not node_id:
                        raise ValueError("DELETE_NODE requires 'node_id'")
                    if record_rollback:
                        original = self.scene_graph.get_node_by_id(node_id)
                        if original:
                            rollback_ops.append({
                                "action": "ADD_NODE",
                                "node_data": copy.deepcopy(original),
                            })
                    ok = self.scene_graph.handle_node_event("remove", {"id": node_id})

                elif action == "ADD_EDGE":
                    edge_data = op.get("edge_data") or {}
                    if record_rollback:
                        rollback_ops.append({
                            "action": "DELETE_EDGE",
                            "edge_data": copy.deepcopy(edge_data),
                        })
                    ok = self.scene_graph.handle_edge_event("add", edge_data)

                elif action == "DELETE_EDGE":
                    edge_data = op.get("edge_data") or {}
                    if record_rollback:
                        full_edge = self._find_edge_for_rollback(edge_data)
                        if full_edge:
                            rollback_ops.append({
                                "action": "ADD_EDGE",
                                "edge_data": copy.deepcopy(full_edge),
                            })
                        else:
                            rollback_ops.append({
                                "action": "ADD_EDGE",
                                "edge_data": copy.deepcopy(edge_data),
                            })
                    ok = self._remove_edge_flexible(edge_data)

                else:
                    ok = False
                    raise ValueError(f"Unknown action: {action}")

                if not ok:
                    all_ok = False
                    errors.append(f"op failed: {action}")

            except Exception as e:
                all_ok = False
                errors.append(f"op error: {op} -> {e}")

        # Record inverse operations; delay cycles come from the event definition
        if record_rollback and rollback_ops:
            rollback_ops.reverse()
            self._rollback_queue.append({
                "ops": rollback_ops,
                "delay_cycles": max(0, rollback_delay_cycles),
            })

        return all_ok, errors
    
    def _find_edge_for_rollback(self, edge_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:  
        """
        Find the full edge information that currently exists in scene_graph using edge_data from the op.
        Prefer exact matching by source/target/type, and fall back to get_edge(source, target) if not found.
        """  
        src = edge_data.get("source")  
        tgt = edge_data.get("target")  
        etype = edge_data.get("type")  
        if src is None or tgt is None:  
            return None  

        # First filter exactly by type
        try:  
            if etype is not None:  
                edges = self.scene_graph.get_edges_from_node(src, edge_type=etype)  
                for e in edges:  
                    if str(e.get("target")) == str(tgt):  
                        return e  

            # If no type is provided or nothing is found, fall back to the unique source/target edge
            edge = self.scene_graph.get_edge(src, tgt)  
            return edge  # May be None
        except Exception:  
            return None  

    def _remove_edge_flexible(self, edge_data: Dict[str, Any]) -> bool:
        """
        Accept multiple delete-edge input forms to match SemanticSceneGraph.handle_edge_event semantics:
          - If edge_id is provided: delete directly.
          - If source/target are provided: build edge_id internally or delete by source/target.
        """
        if "id" in edge_data or "edge_id" in edge_data:
            return self.scene_graph.handle_edge_event("remove", edge_data)

        src = edge_data.get("source")
        tgt = edge_data.get("target")
        if src is None or tgt is None:
            logger.warning(
                "[NewCaseInjector] DELETE_EDGE requires 'id' or ('source','target')"
            )
            return False

        return self.scene_graph.handle_edge_event("remove", {"source": src, "target": tgt})


    def _archive_event(self, event_def: Dict[str, Any], success: bool, errors: List[str]) -> None:
        """
        Archive record after injection:
          - Append to self.injected_events.
        """
        record = {
            "id": event_def.get("id"),
            "category": event_def.get("category"),
            "type": event_def.get("type"),
            "note": event_def.get("note"),
            "trigger": event_def.get("trigger"),
            "success": success,
            "errors": errors,
        }
        self.injected_events.append(record)
        

    def stop(self) -> None:
        """Hard stop: stop polling."""
        self._running = False
