# -*- coding: utf-8 -*-
"""
LLaMAR Verifier Agent Prompt Template
"""
from typing import List


def build_verifier_system_prompt(active_robot_labels: List[str] = None) -> str:
    """Build system prompt for Verifier Agent.

    Uses unified global observation (scene graph), previous action describes only active robots.

    Args:
        active_robot_labels: Subset of robots dispatched in the previous step.
            If None or empty, previous action is not described.

    Returns:
        Full system prompt string.
    """

    return f"""You are an excellent planner who is tasked with helping a multi-robot system complete a task. The robots operate in a shared environment represented as a scene graph with nodes (entities) and edges (relationships).

You will receive a textual description of the environment as a unified scene graph observation, including nodes, edges, and robot states.

### INPUT FORMAT ###
{{Task: description of the task the robots are supposed to do,
Environment observation: a unified scene graph observation describing the current state of the world (nodes, edges, and robot states),
Robots's previous action: the action robot took in the previous step and whether it was successful,
Robots' open subtasks: list of open subtasks from the previous step. If no plan has been already created, this will be None,
Robots' completed subtasks: list of subtasks the robots have already completed. If no subtasks have been completed, this will be None,
Robots' combined memory: description of robots' combined memory,
Execution feedback: feedback from the current step's execution results}}

You will output the following:
* Reason: The reason for why you think a particular subtask should be moved from the open subtasks list to the completed subtasks list.
* Completed Subtasks: The list of subtasks that have been completed by the robots. Note that you can add subtasks to this list only if they have been successfully completed and were in the open subtask list. If no subtasks have been completed at the current step, return an empty list.

The "Completed Subtasks" should be in a list format where the completed subtasks are listed. For example: ["navigate to area_A", "search area_A for target_X"]
Your output should be in the form of a JSON dictionary as shown below.

Example output:
{{"reason": "UAV-1 successfully navigated to area_A and completed the search. The target was found. However, ...",
"completed subtasks": ["navigate to area_A", "search area_A for target_X"]
}}

When you output the completed subtasks, make sure to not forget to include the previous ones in addition to the new ones.
Also, make sure to never add a subtask to completed subtasks before it has successfully been completed.
Let's work this out in a step by step way to be sure we have the right answer.

* NOTE: DO NOT OUTPUT ANYTHING EXTRA OTHER THAN WHAT HAS BEEN SPECIFIED
"""


def build_verifier_user_prompt(
    instruction: str,
    observation: str,
    subtasks_text: str,
    memory: str,
    feedback: str,
    previous_actions: str = "",
) -> str:
    """Build user prompt for Verifier Agent (per-step dynamic content).

    Args:
        instruction: Task instruction text.
        observation: Observation string generated by format_observation().
        subtasks_text: Subtask text generated by format_subtasks().
        memory: Current accumulated memory string.
        feedback: Current step execution feedback text generated by format_feedback().
        previous_actions: Active robots' previous action description
            generated by format_previous_actions().

    Returns:
        User prompt string.
    """
    parts = [
        f"Task: {instruction}",
        observation,
    ]
    if previous_actions:
        parts.append(previous_actions)
    parts.extend([
        subtasks_text,
        f"Robots' combined memory: {memory if memory else 'None'}",
        f"Execution feedback: {feedback}",
    ])
    return "\n".join(parts)
