# -*- coding: utf-8 -*-
"""
Task solver context management module.
Manages initialization and updates for static and dynamic context.
"""
from typing import Dict, Optional, Any

from modules.platform.platform_factory import get_scene_graph
from modules.platform.abstract_scene_graph import AbstractSceneGraph
from modules.task_solver.sgi_planner.prompt.observation import format_observation
from modules.utils.system.logging_utils import dlog


class SolverContextMixin:
    """
    Context management mixin.
    Provides static context initialization and dynamic context refresh.
    """

    def _init_context_static(self) -> None:
        """Initialize static context with low-frequency updates.

        Called once at task start. Contains configuration parameters and goal
        information that remain unchanged throughout the run.
        """
        if not self.context:
            return

        gt = self.context._generated_text

        # Static configuration parameters.
        gt["workspace_root"] = str(self.path_manager.workspace_root)
        gt["planner_mode"] = getattr(self, 'planner_mode', 'full')
        gt["use_environment_model"] = getattr(self, 'use_environment_model', True)

        # Goal information loaded from the dataset and unchanged throughout the run.
        scene_graph: AbstractSceneGraph = get_scene_graph()
        goal = scene_graph.get_goal() if scene_graph else None
        if scene_graph and goal:
            gt['goal'] = goal
            gt['goal_type'] = goal.get("goal_type")
            gt['instruction'] = goal.get("description", "")
        else:
            gt['goal'] = None
            gt['goal_type'] = None
            gt['instruction'] = "No instruction"

        # Area boundaries, category mapping, and runtime parameters.
        gt['area_boundaries'] = scene_graph.get_boundary_features() if scene_graph else {}
        gt['category_map'] = scene_graph.get_all_node_categories() if scene_graph else {}
        gt["real_time_pos_map"] = scene_graph.get_positions_by_entity_type(
            entity_categories=['district', 'area', 'trans_facility', 'building', 'robot', 'prop']
        ) if scene_graph else {}
        gt['runtime_params'] = {}

        self._context_initialized = True

    def _update_hitl_instruction(self, instruction_text: str) -> None:
        """Update the HITL instruction, only triggered by user input in HITL mode."""
        if self.context and instruction_text:
            self.context._generated_text['instruction'] = instruction_text
            dlog(f"HITL instruction updated: {instruction_text[:100]}...",
                 logger=self.logger, level='info')

    def _refresh_context(
        self,
        feedback_data: Optional[Any] = None,
    ) -> None:
        """Refresh dynamic context with high-frequency updates.

        Called on each planning loop to update real-time information.
        Common fields, such as area_boundaries and category_map, are updated
        for all methods.

        Args:
            feedback_data: Feedback data generated by feedback_processor on the SGI path.
        """
        if not self.context:
            return

        gt = self.context._generated_text
        scene_graph: AbstractSceneGraph = get_scene_graph()

        # Common fields updated by all methods.
        if scene_graph:
            gt['area_boundaries'] = scene_graph.get_boundary_features()
            gt['category_map'] = scene_graph.get_all_node_categories()
            gt["real_time_pos_map"] = scene_graph.get_positions_by_entity_type(
                entity_categories=['district', 'area', 'trans_facility', 'building', 'robot', 'prop']
            )

        if getattr(self, 'solver_type', 'sgi') == "sgi":
            # Scene description.
            if getattr(self, 'use_environment_model', True):
                if self.world_model_layer.world_model_manager:
                    try:
                        known_nodes, known_edges = self.world_model_layer.world_model_manager.get_current_world_state()
                        # Get robot_labels.
                        robot_nodes = [
                            n for n in known_nodes
                            if (n.get('properties') or {}).get('category') == 'robot'
                        ]
                        robot_labels = sorted(
                            n.get('properties', {}).get('label', '')
                            for n in robot_nodes
                            if n.get('properties', {}).get('label')
                            and n.get('properties', {}).get('type') in self.robot_type_list
                        )
                        scene_desc = format_observation(known_nodes, known_edges, robot_labels)
                    except Exception:
                        scene_desc = "No scene description available"
                else:
                    scene_desc = "No scene description available"
            else:
                scene_desc = None

            # Real-time positions, available robots, and robot states.
            if scene_graph:
                gt["real_time_pos_map"] = scene_graph.get_positions_by_entity_type(
                    entity_categories=['district', 'area', 'trans_facility', 'building', 'robot', 'prop']
                )
                gt["available_robots"] = scene_graph.get_available_robots(self.robot_type_list)
                gt["robot_states"] = scene_graph.get_robot_states()
            else:
                gt["real_time_pos_map"] = {}
                gt["available_robots"] = {}
                gt["robot_states"] = {}

            compact_plan = self.planning_layer.feedback_processor.build_compact_task_plan()

            gt["scene_desc"] = scene_desc
            gt["feedback_data"] = feedback_data
            gt["task_plan_brief"] = compact_plan
            gt["is_replanning"] = self.replanning_count > 0
