"""Task-conditioned active-search components."""

from .contracts import (
    SearchArea,
    SearchBudget,
    SearchObservation,
    SearchOutcome,
    SearchOutcomeStatus,
    SearchState,
    SearchSuccessCriteria,
    SearchTarget,
    SearchTask,
    TargetDetection,
    Viewpoint,
)
from .policies import (
    ActiveSearchPolicy,
    CoveragePolicy,
    GreedyPriorPolicy,
    RandomPolicy,
    SearchPolicy,
    ViewpointScore,
)
from .execution import SearchSession
from .search_space import (
    CandidateViewpointGenerator,
    SearchCell,
    SearchGrid,
    ViewpointCandidate,
    viewpoint_distance_matrix,
)
from .semantic_map import SemanticFeature, SemanticGridBuilder, normalize_semantic_label
from .search_prior import SearchPrior, SearchPriorProjection, SearchPriorRequest
from .belief import (
    BayesianBeliefUpdater,
    BeliefMap,
    BeliefUpdate,
    BinarySensorModel,
)
from .evaluation import (
    MetricEstimate,
    PolicyAggregate,
    SearchBenchmarkConfig,
    SearchBenchmarkReport,
    SearchBenchmarkRunner,
    SearchBenchmarkScenario,
    SearchEpisodeResult,
    SearchEpisodeRunner,
    default_benchmark_scenarios,
    write_benchmark_report,
)
from .integration import SearchObservationAdapter, SearchSensorFrame

__all__ = [
    "ActiveSearchPolicy",
    "SearchArea",
    "SearchBudget",
    "CoveragePolicy",
    "GreedyPriorPolicy",
    "CandidateViewpointGenerator",
    "BayesianBeliefUpdater",
    "BeliefMap",
    "BeliefUpdate",
    "BinarySensorModel",
    "MetricEstimate",
    "PolicyAggregate",
    "SearchObservation",
    "SearchObservationAdapter",
    "SearchBenchmarkConfig",
    "SearchBenchmarkReport",
    "SearchBenchmarkRunner",
    "SearchBenchmarkScenario",
    "SearchEpisodeResult",
    "SearchEpisodeRunner",
    "SearchOutcome",
    "SearchOutcomeStatus",
    "SearchState",
    "SearchSensorFrame",
    "SearchSuccessCriteria",
    "SearchPolicy",
    "SearchPrior",
    "SearchPriorProjection",
    "SearchPriorRequest",
    "RandomPolicy",
    "SearchSession",
    "SearchCell",
    "SearchGrid",
    "SearchTarget",
    "SearchTask",
    "SemanticFeature",
    "SemanticGridBuilder",
    "TargetDetection",
    "Viewpoint",
    "ViewpointCandidate",
    "ViewpointScore",
    "viewpoint_distance_matrix",
    "default_benchmark_scenarios",
    "normalize_semantic_label",
    "write_benchmark_report",
]
