- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS

- ros_topic_name: /uav/odom
  gz_topic_name: /model/gsi_uav/odometry
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: gz.msgs.Odometry
  direction: GZ_TO_ROS

- ros_topic_name: /uav/imu
  gz_topic_name: /world/gsi_search/model/gsi_uav/link/base_link/sensor/imu/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: gz.msgs.IMU
  direction: GZ_TO_ROS

- ros_topic_name: /uav/camera/image_raw
  gz_topic_name: /world/gsi_search/model/gsi_uav/link/camera_link/sensor/rgb_camera/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- ros_topic_name: /uav/camera/camera_info
  gz_topic_name: /world/gsi_search/model/gsi_uav/link/camera_link/sensor/rgb_camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
  gz_type_name: gz.msgs.CameraInfo
  direction: GZ_TO_ROS

- ros_topic_name: /uav/depth/image_raw
  gz_topic_name: /world/gsi_search/model/gsi_uav/link/camera_link/sensor/depth_camera/depth_image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- ros_topic_name: /uav/lidar/points
  gz_topic_name: /world/gsi_search/model/gsi_uav/link/lidar_link/sensor/gpu_lidar/scan/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  gz_type_name: gz.msgs.PointCloudPacked
  direction: GZ_TO_ROS

- ros_topic_name: /uav/cmd_vel
  gz_topic_name: /model/gsi_uav/cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
  gz_type_name: gz.msgs.Twist
  direction: ROS_TO_GZ
