# -*- coding: utf-8 -*-
"""
LipLLM Dependency Graph Agent - Skill dependency graph generation

Inherits ActionNode, uses LipLLM prompt templates to build prompts,
parses LLM output in "skill_A -> skill_B" format, builds an acyclic dependency graph.
Automatically retries on cycles, up to n_attempts times.
"""
import logging
import re
from typing import List, Optional, Set, Tuple

import networkx as nx

from modules.task_solver.llm_framework.file import Logger
from modules.task_solver.llm_framework.core.context import WorkflowContext
from modules.task_solver.llm_framework.core.action import ActionNode
from modules.task_solver.baseline_planners.lipllm.prompt.lipllm_prompt import (
    build_dependency_graph_system_prompt,
    build_dependency_graph_user_prompt,
)
from modules.task_solver.baseline_planners.lipllm.prompt.lipllm_examples import (
    DEPENDENCY_FEW_SHOT_EXAMPLES,
)
from modules.utils.system.logging_utils import dlog

logger = logging.getLogger(__name__)


# Regex to match dependency edges: "skill_A → skill_B" or "skill_A -> skill_B"
# Supports both Unicode arrow (→) and ASCII arrow (->)
_EDGE_PATTERN = re.compile(
    r"^\s*(.+?)\s*(?:→|->)\s*(.+?)\s*$",
    re.MULTILINE,
)


def parse_dependency_edges(
    response: str,
    valid_skills: Optional[Set[str]] = None,
) -> List[Tuple[str, str]]:
    """Parse LLM response text into a list of directed edge tuples.

    Extracts edges in the format ``skill_A → skill_B`` (or ``->``).
    Optionally filters to only include edges whose endpoints are in
    *valid_skills*.

    Args:
        response: Raw LLM response text.
        valid_skills: If provided, only edges where both endpoints are
            in this set will be included.

    Returns:
        List of (source, target) tuples.
    """
    if response.strip().lower() == "none":
        return []

    edges: List[Tuple[str, str]] = []
    for match in _EDGE_PATTERN.finditer(response):
        src = match.group(1).strip()
        tgt = match.group(2).strip()
        if not src or not tgt:
            continue
        if valid_skills is not None:
            if src not in valid_skills or tgt not in valid_skills:
                logger.warning(
                    f"Skipping edge with unknown skill: '{src}' → '{tgt}'"
                )
                continue
        edges.append((src, tgt))
    return edges


class DependencyGraphAgent(ActionNode):
    """Dependency graph agent — generates directed dependency edges between skills.

    Key features:
    - Receives the full skill list, outputs all dependency edges at once
    - Parses "skill_A -> skill_B" format
    - Builds networkx DiGraph and detects cycles; retries on cycles
    - Returns empty dependency set after all retries are exhausted

    Attributes:
        use_few_shot: Whether to include few-shot examples in the prompt.
    """

    def __init__(
        self,
        logger_: Logger,
        context: WorkflowContext,
        model_family: str = None,
        model_name_override: str = None,
        use_few_shot: bool = False,
    ):
        super().__init__(
            logger=logger_,
            context=context,
            next_text="",
            node_name="LipLLM_DependencyGraph",
            model_family=model_family,
            model_name_override=model_name_override,
        )
        self.use_few_shot: bool = use_few_shot
        self.llm_call_count: int = 0

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _build_prompt(self, skill_list: Optional[List[str]] = None) -> None:
        """Build the full prompt for DependencyGraphAgent.

        Args:
            skill_list: Skill list generated by SkillListAgent.
                If None, builds an empty prompt (for ActionNode compat).
        """
        if skill_list is None:
            skill_list = []

        instruction = self.context._generated_text.get("instruction", "")

        system_prompt = build_dependency_graph_system_prompt()
        user_prompt = build_dependency_graph_user_prompt(
            instruction=instruction,
            skill_list=skill_list,
        )

        parts = [system_prompt]

        # Few-shot examples
        if self.use_few_shot:
            for msg in DEPENDENCY_FEW_SHOT_EXAMPLES:
                parts.append(f"\n{msg['content']}")

        parts.append(f"\n{user_prompt}")

        self.prompt = "\n".join(parts)

    # ------------------------------------------------------------------
    # Response parsing
    # ------------------------------------------------------------------

    async def _process_response(self, response: str) -> str:
        """Parse LLM output, extract skill_A -> skill_B format edges.

        This override stores the raw response for later edge extraction

        Args:
            response: Raw LLM response text.

        Returns:
            Raw response text.
        """
        return response.strip()

    # ------------------------------------------------------------------
    # Dependency graph generation with retry
    # ------------------------------------------------------------------

    async def generate_dependencies(
        self,
        skill_list: List[str],
        n_attempts: int = 5,
    ) -> Tuple[nx.DiGraph, List[Tuple[str, str]]]:
        """Generate an acyclic dependency graph, retrying on cycles.

        Flow:
        1. Build prompt and call LLM
        2. Parse response to extract edges
        3. Build DiGraph and detect cycles
        4. Retry on cycles, up to n_attempts
        5. Return edge-less graph after all retries are exhausted

        Args:
            skill_list: Skill list generated by SkillListAgent.
            n_attempts: Max retry count (default 5).

        Returns:
            (graph, edges) — networkx DiGraph and edge list.
        """
        valid_skills = set(skill_list)

        for attempt in range(n_attempts):
            # Build prompt and call LLM
            self._build_prompt(skill_list)

            try:
                response_text = await self._run_single_attempt()
            except Exception as e:
                logger.error(
                    f"LLM call failed on attempt {attempt + 1}: {e}"
                )
                continue

            # Parse edges
            edges = parse_dependency_edges(response_text, valid_skills)

            # Build graph
            graph = nx.DiGraph()
            graph.add_nodes_from(skill_list)
            graph.add_edges_from(edges)

            # Check for cycles
            try:
                cycle = nx.find_cycle(graph)
                logger.warning(
                    f"Cycle detected on attempt {attempt + 1}: {cycle}. Retrying..."
                )
                continue
            except nx.NetworkXNoCycle:
                # No cycle — success
                dlog(
                    f"DependencyGraphAgent: generated {len(edges)} edges "
                    f"(acyclic) on attempt {attempt + 1}",
                    logger=self.logger,
                    level="info",
                )
                return graph, edges

        # All attempts exhausted — return graph with no edges
        logger.error(
            f"DependencyGraphAgent: all {n_attempts} attempts produced "
            f"cyclic graphs. Returning empty dependency set."
        )
        graph = nx.DiGraph()
        graph.add_nodes_from(skill_list)
        return graph, []

    async def _run_single_attempt(self) -> str:
        """Execute a single LLM call.

        Directly uses the underlying GPT instance to send the current prompt,
        bypassing ActionNode's built-in retry mechanism.

        Returns:
            LLM response text.
        """
        if self.prompt is None:
            raise ValueError("Prompt is required for DependencyGraphAgent")

        # Structured markers for offline token counting
        self.logger.log("<!-- LLM_PROMPT_START -->", level="info", print_to_terminal=False)
        dlog(f"Prompt:\n {self.prompt}", logger=self.logger, level="debug")
        self.logger.log("<!-- LLM_PROMPT_END -->", level="info", print_to_terminal=False)

        llm = self._ActionNode__llm
        response = await llm.ask(self.prompt)
        self.llm_call_count += 1

        self.logger.log("<!-- LLM_RESPONSE_START -->", level="info", print_to_terminal=False)
        dlog(f"Response:\n {response}", logger=self.logger, level="info")
        self.logger.log("<!-- LLM_RESPONSE_END -->", level="info", print_to_terminal=False)
        return response
